# Generated by Django 5.2 on 2025-05-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionist',
            name='price',
            field=models.PositiveIntegerField(default=19990),
        ),
    ]
