# Generated by Django 5.2 on 2025-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_nutritionist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=19990, max_digits=10),
        ),
    ]
